name: Build Assets

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Vite Assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Commit built assets back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: build assets [skip ci]"
          file_pattern: "public/build/**"
          push_options: '--force'
